name: Hello World

on:
  push:
    branches: [ test ]

jobs:
  changed-files:
    runs-on: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get changed files in the last commit
        run: git log
